# Generated by Django 5.0.1 on 2024-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionCLO', models.CharField(max_length=50)),
            ],
        ),
    ]
