# Generated by Django 5.0.1 on 2024-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clo',
            name='knowledge_level',
            field=models.CharField(default='Bas', max_length=50),
        ),
    ]
