# Generated by Django 5.0.1 on 2024-01-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clo_knowledge_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='clo',
            name='knowledge_level',
            field=models.CharField(max_length=50),
        ),
    ]
