# Generated by Django 5.0.1 on 2024-01-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_reference_alter_clo_knowledge_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_level', models.IntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mission')),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peo')),
            ],
        ),
    ]
