# Generated by Django 5.0.1 on 2024-01-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapping',
            old_name='mission',
            new_name='mission_id',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='peo',
            new_name='peo_id',
        ),
    ]
