# Generated by Django 5.0.1 on 2024-01-05 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_mission_mapping_mission_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapping',
            old_name='mission_id',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='peo_id',
            new_name='peo',
        ),
        migrations.AlterField(
            model_name='mapping',
            name='correlation_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
