# Generated by Django 5.0.1 on 2024-01-11 15:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_mission_id_mapping_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PloMapPeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peo')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plo')),
            ],
        ),
    ]
