# Generated by Django 5.0.1 on 2024-01-13 11:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plomappeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloMapPlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clo')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plo')),
            ],
        ),
    ]
