# Generated by Django 5.0.1 on 2024-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_attitude_co_knowledge_skill_vision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.CharField(max_length=50)),
                ('ending', models.CharField(max_length=50)),
            ],
        ),
    ]
