# Generated by Django 5.0.1 on 2024-01-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='peo',
            name='upCurriculum',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.curriculum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peo',
            name='upSyllabus',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.syllabus'),
            preserve_default=False,
        ),
    ]
