# Generated by Django 5.0.1 on 2024-01-19 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_peo_upcurriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='peo',
            name='upCurriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.curriculum'),
        ),
        migrations.AddField(
            model_name='peo',
            name='upSyllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.syllabus'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='peo',
            name='descriptionPEO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
