# Generated by Django 5.0.1 on 2024-01-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_peo_upcurriculum_peo_upsyllabus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clo',
            name='descriptionCLO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clo',
            name='knowledge_level',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='co',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
