# Generated by Django 5.0.1 on 2024-01-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_attitude_description_alter_clo_descriptionclo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peo',
            name='upCurriculum',
        ),
        migrations.AlterField(
            model_name='peo',
            name='upSyllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.syllabus'),
        ),
    ]
