# Generated by Django 5.0.1 on 2024-01-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_peo_upcurriculum_alter_peo_upsyllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='upSyllabus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.syllabus'),
        ),
    ]
