# Generated by Django 5.0.1 on 2024-01-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mapping_upsyllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='plo',
            name='upSyllabus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.syllabus'),
        ),
        migrations.AlterField(
            model_name='plo',
            name='descriptionPLO',
            field=models.CharField(max_length=200),
        ),
    ]
