# Generated by Django 5.0.1 on 2024-01-26 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_plo_upsyllabus_alter_plo_descriptionplo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plomappeo',
            name='upSyllabus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.syllabus'),
        ),
    ]
