# Generated by Django 5.0.1 on 2024-01-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_co_upcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='clo',
            name='upCourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
