# Generated by Django 5.0.1 on 2024-01-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_clo_upcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='clomapplo',
            name='upCourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
