# Generated by Django 5.0.1 on 2024-01-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_clomapplo_upcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='attitude',
            name='upCourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='book_reference',
            name='upCourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='upCourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='skill',
            name='upCourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
