# Generated by Django 5.0.1 on 2024-02-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='upCourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
