# Generated by Django 5.0.1 on 2024-02-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_assessment_upcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='final',
        ),
    ]
