# Generated by Django 5.0.1 on 2024-02-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_assessment_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('prerequisites', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('contact_hours', models.IntegerField()),
                ('total_lectures', models.IntegerField()),
                ('class_tests', models.IntegerField()),
                ('final_exam', models.IntegerField()),
                ('faculty', models.CharField(max_length=255)),
                ('rationale', models.TextField()),
                ('upCourse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
    ]
