# Generated by Django 5.0.1 on 2024-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_courseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
