# Generated by Django 5.0.1 on 2024-04-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_courseinfo_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('nonfaceToface', models.IntegerField()),
                ('lecture', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('practical', models.IntegerField()),
                ('others', models.IntegerField()),
                ('ilearn', models.IntegerField()),
                ('totalSlt', models.IntegerField()),
                ('atts', models.ManyToManyField(default=[], to='api.attitude')),
                ('clos', models.ManyToManyField(default=[], to='api.clo')),
                ('knows', models.ManyToManyField(default=[], to='api.knowledge')),
                ('skills', models.ManyToManyField(default=[], to='api.skill')),
                ('upCourse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
    ]
