# Generated by Django 5.0.1 on 2024-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_outline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineLast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=123)),
                ('percentage', models.IntegerField(blank=True)),
                ('f2f', models.IntegerField(blank=True)),
                ('nonf2f', models.IntegerField(blank=True)),
                ('stl', models.IntegerField(blank=True)),
            ],
        ),
    ]
