# Generated by Django 5.0.1 on 2024-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_outlinelast_upcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlinelast',
            name='f2f',
        ),
        migrations.RemoveField(
            model_name='outlinelast',
            name='name',
        ),
        migrations.RemoveField(
            model_name='outlinelast',
            name='nonf2f',
        ),
        migrations.RemoveField(
            model_name='outlinelast',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='outlinelast',
            name='stl',
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='attendanceP',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='finalF2F',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='finalP',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='finalnF2F',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='finalstl',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='tutF2F',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='tutP',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='tutStl',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
        migrations.AddField(
            model_name='outlinelast',
            name='tutnF2F',
            field=models.IntegerField(blank=True, default=3, max_length=123),
        ),
    ]
