# Generated by Django 5.0.1 on 2024-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_outlinelast_f2f_remove_outlinelast_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinelast',
            name='attendanceP',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='finalF2F',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='finalP',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='finalnF2F',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='finalstl',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='tutF2F',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='tutP',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='tutStl',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='outlinelast',
            name='tutnF2F',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
