# Generated by Django 5.0.6 on 2024-05-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_outlinelast_attendancep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
