# Generated by Django 5.0.6 on 2024-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_outline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
